export const COLOR_LOADING = 'COLOR_LOADING'
export const COLOR_SUCCESS = 'COLOR_SUCCESS'
export const COLOR_FAIL = 'COLOR_FAIL'

export const PRODUCT_LOADING = 'PRODUCT_LOADING'
export const PRODUCT_SUCCESS = 'PRODUCT_SUCCESS'
export const PRODUCT_FAIL = 'PRODUCT_FAIL'
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT'